apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
nameSuffix: -green
commonLabels:
  version: green
  environment: production
patches:
- target:
    kind: Deployment
    name: sparkle-gateway
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
